### PR TITLE
Initial revision of custom resource rewrite

### LINKED ISSUE #78: chef-rundeck fails on Ubuntu
Because of something weird with how the job is setup with runit, it errors when building the XML response.

When i run the command manually with it disabled in runit, it works ok.

```
[2016-03-16T18:09:56+00:00] ERROR: === could not generate xml for {"name"=>"foo.bar", "chef_environment"=>"production", "run_list"=>role[base], "recipes"=>[], "roles"=>["base"], "fqdn"=>"foo.bar", "hostname"=>"foo.bar", "kernel_machine"=>"x86_64", "kernel_os"=>"GNU/Linux", "platform"=>"ubuntu", "platform_version"=>"14.04", "tags"=>["statsd"]}:  undefined method `unpack' for nil:NilClass
[2016-03-16T18:09:56+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/mixin/xml_escape.rb:109:in `rescue in xml_escape'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/mixin/xml_escape.rb:106:in `xml_escape'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-rundeck-2.2.0/lib/chef-rundeck.rb:188:in `build_node'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-rundeck-2.2.0/lib/chef-rundeck.rb:152:in `block in build_project'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-rundeck-2.2.0/lib/chef-rundeck.rb:140:in `each'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-rundeck-2.2.0/lib/chef-rundeck.rb:140:in `build_project'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-rundeck-2.2.0/lib/chef-rundeck.rb:82:in `block in configure'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'\n/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'\n/opt/chef/embedded/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'\n/opt/chef/embedded/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'\n/opt/chef/embedded/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
[2016-03-16T18:09:56+00:00] INFO: nodes complete (project: 'default', total: 396, failed: 0)
[2016-03-16T18:09:56+00:00] DEBUG: #<File:/tmp/chef-rundeck-default.xml>
```

### LINKED ISSUE #85: Remote database url support?
From the rundeck docs [here](http://rundeck.org/2.6.6/administration/setting-up-an-rdb-datasource.html)
We can see that rundeck supports specifying an external db source url as seen in this snippet of code:

```
dataSource.url = jdbc:oracle:thin:@localhost:1521:XE
dataSource.driverClassName = oracle.jdbc.driver.OracleDriver
dataSource.username = dbuser
dataSource.password = dbpass
dataSource.dialect = org.hibernate.dialect.Oracle10gDialect
```

This is how I setup the code:

```
# External Database properties
default['rundeck']['rdbms']['enable'] = 'true'
default['rundeck']['rdbms']['type'] = 'oracle'
default['rundeck']['rdbms']['location'] = 'xxx.xxx.xxx.xxx'
default['rundeck']['rdbms']['dbname'] = 'dbname'
default['rundeck']['rdbms']['dbuser'] = 'user'
default['rundeck']['rdbms']['dbpassword'] = 'password'
default['rundeck']['rdbms']['dialect'] = 'Oracle10gDialect'
default['rundeck']['rdbms']['port'] = 'xxxx'
```

When I check the file /etc/rundeck/rundeck-config.properties it looks like most of the settings are there except for one

```
dataSource.url = jdbc:oracle:thin:@:xxx.xxx.xxx.xxx:PORT:XE
dataSource.driverClassName = oracle.jdbc.driver.OracleDriver
dataSource.dialect = org.hibernate.dialect.Oracle10gDialect
dataSource.dbCreate=update
dataSource.username =user
dataSource.password =password
```

I need to have the XE part at the end changed, but it seems to always attach that no matter what I do and the docs make no mention of how that would be changed.

### LINKED ISSUE #98: If rdbms data bag not present, cookbook errors out
When using node attributes for rdbms, the cookbook fails out saying "404 not found" as it is trying to load a data bag which does not exist. We should still use the node attributes if the data bag doesn't exist.

### LINKED ISSUE #145: Rundeck app user does not need sudo permissions
Seems like the rundeck user does not need sudo permissions, but it is given permission to run all commands with sudo no password.

https://github.com/Webtrends/rundeck/blob/8a806f4024ff13662ac38a26330f3fe9afddb47b/recipes/node_unix.rb#L61-L64

### LINKED ISSUE #169: Cookbook won't connect to the rundeck server due to outdated web.xml
### Cookbook version
3.2.1

### Chef-client version
12.17.44

### Rundeck version
rundeck-2.8.4-1.33.GA

### Platform Details
macOS Sierra 10.12.5 /w Vagrant Driver

### Scenario:
Installing rundeck cookbook.

### Steps to Reproduce:
Just run the cookbook OOTB /w the Rundeck version above.

### Expected Result:
The cookbook should proceed to the next steps after having successful connection to the Rundeck server. 

### Actual Result:
The cookbook gets stuck on connecting to Rundeck stage. It reaches timeout after a certain time.

### How I solved the issue:
Had to make a few changes in web.xml. These changes were takes from the Official Rundeck RPM (while preserving all the cookbook-template related sections).

### LINKED ISSUE #181: rundeck_api_client library LoadError in dokken testing with ChefDK > 2.0.28
With the stable ChefDK 2.1.11, any kitchen-dokken test and so Travis build fails with the below. 

```
-----> Installing Serverspec..
-----> serverspec installed (version 2.40.0)
/opt/chef/embedded/bin/ruby -I/opt/verifier/suites/serverspec -I/opt/verifier/gems/gems/rspec-support-3.6.0/lib:/opt/verifier/gems/gems/rspec-core-3.6.0/lib /opt/chef/embedded/bin/rspec --pattern /opt/verifier/suites/serverspec/\*\*/\*_spec.rb --color --format documentation --default-path /opt/verifier/suites/serverspec
Building native extensions.  This could take a while...
An error occurred while loading /opt/verifier/suites/serverspec/apache_spec.rb.
Failure/Error: load '/opt/kitchen/cookbooks/rundeck/libraries/rundeck_api_client.rb'
LoadError:
  cannot load such file -- /opt/kitchen/cookbooks/rundeck/libraries/rundeck_api_client.rb
  
# /opt/verifier/suites/serverspec/spec_helper.rb:13:in `load'
# /opt/verifier/suites/serverspec/spec_helper.rb:13:in `rescue in <top (required)>'
# /opt/verifier/suites/serverspec/spec_helper.rb:8:in `<top (required)>'
# /opt/verifier/suites/serverspec/apache_spec.rb:1:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- /tmp/kitchen/cookbooks/rundeck/libraries/rundeck_api_client.rb
#   /opt/verifier/suites/serverspec/spec_helper.rb:10:in `load'
```

Relevant spec_helper code:
https://github.com/sous-chefs/rundeck/blob/b91dddd452fcdbb318763998349d2dff718de1c4/test/integration/default/serverspec/spec_helper.rb#L7-L14

It seems that the kitchen_sandbox directory /opt/kitchen is now not available during the verify phase, which we need for loading the api library. Possibly related to recent [kitchen-dokken changes](https://github.com/someara/kitchen-dokken/blob/master/CHANGELOG.md#265) that [cleanup kitchen_sandbox](https://github.com/someara/kitchen-dokken/issues/118)?

## ChefDK 2.1.11 and kitchen-dokken 2.6.1

Adding output of `Dir["/opt/kitchen/*"]` to server.rb recipe so it executes during converge phase:
```
["/opt/kitchen/cache",
 "/opt/kitchen/client.pem",
 "/opt/kitchen/client.rb",
 "/opt/kitchen/clients",
 "/opt/kitchen/cookbooks",
 "/opt/kitchen/data_bags",
 "/opt/kitchen/dna.json",
 "/opt/kitchen/nodes",
 "/opt/kitchen/validation.pem"]
```
Adding same to spec_helper so it executes during verify phase :
```
[]
```
Poking about inside the container shows:
```
root@dokken:/# ls -lh /opt
ls: cannot access /opt/kitchen: No such file or directory
total 4.0K
drwxrwxr-x 5 root root 4.0K Sep  6 12:13 chef
d????????? ? ?    ?       ?            ? kitchen
drwxr-xr-x 1 1000 ftp   170 Sep  6 13:30 verifier
```

## ChefDK 2.2.1 and kitchen-dokken 2.6.5

Tested locally and looks to be slightly improved in current channel [ChefDK 2.2.1](https://github.com/chef/chef-dk/blob/master/CHANGELOG.md#v221-2017-09-04) with `kitchen-dokken` 2.6.5 where at least the directory isn't borked, but is now just empty instead:
```
root@dokken:/# ls -lh /opt/kitchen/
total 0
```

## ChefDK 2.0.28 and kitchen-dokken 2.5.1
Going back to ChefDK 2.0.28 fixes the problem entirely, and tests pass without the LoadError:
```
root@dokken:/# ls -lh /opt/kitchen/
total 16K
drwxr-xr-x 1 1000 staff  170 Sep  6 15:20 cache
-rw------- 1 1000 staff 1.7K Sep  6 15:20 client.pem
-rw-r--r-- 1 1000 staff  679 Sep  6 15:20 client.rb
drwxr-xr-x 1 1000 staff  102 Sep  6 15:20 clients
drwxr-xr-x 1 1000 staff  646 Sep  6 15:20 cookbooks
drwxr-xr-x 1 1000 staff  136 Sep  6 15:20 data_bags
-rw-r--r-- 1 1000 staff  241 Sep  6 15:20 dna.json
drwxr-xr-x 1 1000 staff  102 Sep  6 15:20 nodes
-rw-r--r-- 1 1000 staff 1.7K Sep  6 15:20 validation.pem
```

### LINKED ISSUE #189: Rundeck 3.x support
When are we going to see rundeck 3.x support? The rundeck 3.x binaries has a different naming convention which is not backwards compatible.

### LINKED ISSUE #190: Broken build
Failing build: https://travis-ci.org/sous-chefs/rundeck/jobs/421278908

Build failure message:
```
FC113: Resource declares deprecated use_inline_resources: ./providers/plugin.rb:1
FC113: Resource declares deprecated use_inline_resources: ./providers/plugin.rb:21
FC113: Resource declares deprecated use_inline_resources: ./providers/project.rb:1
FC113: Resource declares deprecated use_inline_resources: ./providers/user.rb:1
FC113: Resource declares deprecated use_inline_resources: ./providers/user.rb:21
FC120: Do not set the name property directly on a resource: ./recipes/server_install.rb:68
FC121: Cookbook depends on cookbook made obsolete by Chef 14: ./metadata.rb:1
FC122: Use the build_essential resource instead of the recipe: ./recipes/_connect_rundeck_api_client.rb:3
```

Hopefully this may be low hanging fruit!

### PR DESCRIPTION
**Pull request by PowerSchill**
### Description

Converts recipes to custom resources. Major changes.

### Issues Resolved

Closes #78 
Closes #85 
Closes #98 
Closes #145
Closes #169
Closes #181
Closes #187 
Closes #189 
Closes #190 

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big Pull Request.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: resources/apache.rb [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#
+
+include RundeckCookbook::Helpers
+
+property :use_ssl, [true, false], default: false
+property :cert_name, String, default: node['hostname']
```
Comment (tas50) [inline resources/apache.rb]: You'll want to lazily eval this:

```suggestion
property :cert_name, String, default: lazy { node['hostname'] }
```

File: resources/apache.rb [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+property :cert_contents, String
+property :key_contents, String, sensitive: true
+property :ca_cert_name, String
+property :ca_cert_contents, String
+property :hostname, String, default: "rundeck.#{node['domain']}"
```
Comment (tas50) [inline resources/apache.rb]: This will need to be lazy as well
```suggestion
property :hostname, String, default: lazy { "rundeck.#{node['domain']}" }
```

File: resources/apache.rb [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+property :email, String, default: "rundeck@#{node['domain']}"
```
Comment (tas50) [inline resources/apache.rb]: and this
```suggestion
property :email, String, default: lazy { "rundeck@#{node['domain']}" }
```

File: resources/apache.rb [hunk 4]
```diff
@@ -0,0 +1,118 @@
...
+property :allow_local_https,  [true, false], default: true
+property :webcontext, String, default: '/'
+property :port, Integer, default: 4440
+
+action :install do
+  include_recipe 'apache2'
```
Comment (tas50) [inline resources/apache.rb]: Since this is using the old apache2 cookbook setup you'll need to pin to the older version of the cookbook in the metadata

File: resources/plugin.rb [hunk 5]
```diff
@@ -17,10 +17,54 @@
 # limitations under the License.
 #
 
-actions :create, :remove
+include RundeckCookbook::Helpers
 
-default_action :create
+property :name, String,
+         name_attribute: true,
```
Comment (tas50) [inline resources/plugin.rb]:
```suggestion
         name_property: true,
```

File: resources/plugin.rb [hunk 6]
```diff
@@ -17,10 +17,54 @@
...
+         description: 'Name of the plugin to install'
```
Comment (tas50) [inline resources/plugin.rb]: The description fields are only available in some of the last releases of Chef 13 and then Chef 14+ so be aware if you use these you're requiring fairly recent Chef releases and the metadata should be bumped to reflect that.

File: resources/plugin.rb [hunk 7]
```diff
@@ -17,10 +17,54 @@
...
+    backup false
+    action :create
+    notifies (new_resource.restart_on_config_change ? :restart : :nothing), 'service[rundeckd]', :delayed
+  end
+
+  service 'rundeckd' do
+    case node['platform']
+    when 'ubuntu'
+      if node['platform_version'].to_f >= 16.04
+        provider Chef::Provider::Service::Systemd
```
Comment (tas50) [inline resources/plugin.rb]: Selecting the provider shouldn't be necessary with modern chef. You'll want to double check this, but even in the later releases of Chef 12 we just did the right thing here.

File: resources/repository.rb [hunk 8]
```diff
@@ -0,0 +1,61 @@
...
+    'http://rundeck.org/keys/BUILD-GPG-KEY-Rundeck.org.key'
+  else # 'debian'
+    'https://bintray.com/user/downloadSubjectPublicKey?username=bintray'
+  end
+}
+property :gpgcheck, [true, false], default: true
+
+action :install do
+  case node['platform_family']
+  when 'rhel'
```
Comment (tas50) [inline resources/repository.rb]: There's case statements above for amazon, but not here. You probably want to add amazon here

File: metadata.rb [hunk 9]
```diff
@@ -6,12 +6,12 @@
 long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
 version          '4.2.0'
 depends          'java'
-depends          'apache2'
+depends          'apache2', '~> 5.2.1'
```
Comment (tas50) [inline metadata.rb]: This should probably just be < 6 so we don't constrain things too much. We just can't rely on 6.x

File: metadata.rb [hunk 10]
```diff
@@ -5,25 +5,13 @@
...
-recipe 'rundeck::server_dependencies', 'Use this recipe to install the dependencies for the rundeck server install'
-recipe 'rundeck::chef-rundeck', 'Use this recipe to install the chef rundeck integration component, by default it is recommened to install on the chef server.'
-recipe 'rundeck::default', 'Use this recipe to manage the node as a target in rundeck, this recipe is included in rundeck::server'
-recipe 'rundeck::node_unix', 'Unix\Linux platform configuration, do not use on a node, the default recipe uses this implmentation'
-recipe 'rundeck::node_windows', 'Windows platform configuration, do not use on a node, the default recipe uses this implmentation'
-
 source_url "https://github.com/sous-chefs/#{name}"
 issues_url "https://github.com/sous-chefs/#{name}/issues"
-chef_version '>= 12.1' if respond_to?(:chef_version)
+chef_version '>= 13.0' if respond_to?(:chef_version)
```
Comment (damacus) [inline metadata.rb]:
```suggestion
chef_version '>= 13.0'
```

We don't need this bit anymore

File: metadata.rb [hunk 11]
```diff
@@ -5,25 +5,13 @@
 description      'Installs and configures Rundeck 2.x'
 long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
 version          '4.2.0'
-depends          'runit'
-depends          'sudo'
 depends          'java'
-depends          'apache2'
-depends          'build-essential'
+depends          'apache2', '~> 5.2.1'
```
Comment (damacus) [inline metadata.rb]:
```suggestion
depends          'apache2', '< 6.0.0'
```
